### ISSUE TITLE
🚀 [Feature] : Join Newsletter Section

### ISSUE THREAD

**Issue by xuelink** [langx/website#30]
**Is your feature request related to a problem? Please describe.**
- It will increase our marketing..
- Catch to first contact users.

**Describe alternatives you've considered**
<img width="920" alt="Screenshot 2024-02-20 at 2 23 37 PM" src="https://github.com/languageXchange/website/assets/3280475/b1d380a8-ac4f-4125-a6f0-9847a5574400">

**Additional context**
Use Sendgrip API to push to newsletter email list.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by jakebogan01** [comment]
@xuelink I created a PR [here](https://github.com/langx/website/pull/61)
