### ISSUE TITLE
🚀 [Feature] : Add Testimontals Section

### ISSUE THREAD

**Issue by xuelink** [langx/website#34]
**Is your feature request related to a problem? Please describe.**
Customers often seek reassurance and validation before making a purchasing decision. Without a testimonials section, they may lack insight into the positive experiences of previous customers, potentially leading to hesitation or uncertainty.

**Describe the solution you'd like**
I propose adding a testimonials section to our platform where satisfied customers can share their experiences and feedback. This section would prominently display quotes, ratings, and possibly even photos or videos from satisfied customers, providing social proof and building trust with potential customers.

**Describe alternatives you've considered**
An alternative could be integrating customer reviews from third-party platforms, but having an in-house testimonials section allows for more control over the content and presentation. Additionally, it fosters a sense of community within our platform.

**Additional context**
Adding a testimonials section aligns with our goal of enhancing user trust and engagement. It can be strategically placed on product pages or the homepage to maximize visibility and impact.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
## iOS Reviews

**Great!! ⭐⭐⭐⭐⭐**
by Julia Pettersson Westin – Apr 10, 2024
Even tho it’s still in a developing process, everything is very good and the app is really helpful!

    Version 0.9.1 Sweden

**:D  ⭐⭐⭐⭐⭐**
by Emerald-Princess – Feb 21, 2024
Good looking, easy to handle and contact happens really quick :D

    Version 0.5.15 Germany

**An alternative app to other apps language exchange apps  ⭐⭐⭐⭐⭐**
by Burak12332221 – Feb 20, 2024
I like the interface and using. It s a very new app so my advise would be to improve the process of joining this community. Maybe an iq test at first to join :)

    Version 0.5.15 United States

**Супер 😊 ⭐⭐⭐⭐⭐**
by Kate Pas – Feb 20, 2024
Хорошее приложение для изучения языков, которое постоянно улучшается, в основном все действительно заинтерисованы в изучении языков, нет мошенников как в других приложениях, спасибо большое за отличное прилиложение для языкового обмена🙌🏼😌✨

    Version 0.5.14 Colombia

**Useful app ⭐⭐⭐⭐⭐**
by nesrincetin – Feb 13, 2024
It's a great app where you can meet new people and practice

    Version 0.5.7 Türkiye

**The best app ⭐⭐⭐⭐⭐**
by oyusnskska – Feb 8, 2024
The best app dor language learning

    Version 0.5.3 Türkiye

**Super duper ⭐⭐⭐⭐⭐**
by Tech Lavır – Jan 20, 2024
An emerging app with a promising future! Exciting features and a user-friendly interface make this application a potential game-changer in the world of language exchange. Keep an eye on it for innovative experiences and growth! I highly recommend it!

    Version 0.3.3.1 Türkiye

**Try and see the difference than others ⭐⭐⭐⭐⭐**
by Penmek – Jan 15, 2024
New and better than any other lang exchance app in the market.

    Version 0.3 Canada

**Comment by xuelink** [comment]
## Android Reviews (some of them)

<img width="1101" alt="Screenshot 2024-04-18 at 2 14 56 AM" src="https://github.com/langxapp/website/assets/3280475/8edba282-eb4f-4ef7-ae6d-73ae3518e52e">
<img width="1158" alt="Screenshot 2024-04-18 at 2 15 03 AM" src="https://github.com/langxapp/website/assets/3280475/c4c95153-00d4-4046-ac65-c4313636026c">
<img width="996" alt="Screenshot 2024-04-18 at 2 15 11 AM" src="https://github.com/langxapp/website/assets/3280475/2a3779df-0f25-4493-a2ee-c48ea33a1641">
<img width="1033" alt="Screenshot 2024-04-18 at 2 15 18 AM" src="https://github.com/langxapp/website/assets/3280475/dac8cde5-9d2e-4340-afad-d1e93d2691fe">
<img width="1086" alt="Screenshot 2024-04-18 at 2 15 31 AM" src="https://github.com/langxapp/website/assets/3280475/54ae8d49-0e31-4502-aaf3-94318d5ade72">
<img width="1038" alt="Screenshot 2024-04-18 at 2 15 42 AM" src="https://github.com/langxapp/website/assets/3280475/19cede15-941a-4d33-9fd9-657131ad5378">
<img width="1098" alt="Screenshot 2024-04-18 at 2 15 54 AM" src="https://github.com/langxapp/website/assets/3280475/548d6ee3-f7fe-4347-93ed-c8358d53b923">

**Comment by xuelink** [comment]
@jakebogan01 You can pick any of them which fits your work/template ! :)

**Comment by jakebogan01** [comment]
@xuelink thank you!

**Comment by jakebogan01** [comment]
@xuelink hey do you have the link to those google reviews?

**Comment by xuelink** [comment]
@jakebogan01 can u please check your email, i ve sent you an invitation of our google play store account

**Comment by jakebogan01** [comment]
@xuelink Thank you, looks like I need permission to see the reviews and analytics

![image](https://github.com/langx/website/assets/66225768/b340eed5-8ffd-429a-8e87-1eafbd2649ff)

**Comment by xuelink** [comment]
@jakebogan01 i think you can see now :D
<img width="936" alt="Screenshot 2024-04-19 at 1 41 56 PM" src="https://github.com/langx/website/assets/3280475/5b09ccef-bc22-4660-b854-9fdafde0a289">

**Comment by jakebogan01** [comment]
@xuelink Thank you, I made a PR [here](https://github.com/langx/website/pull/59)
