### ISSUE TITLE
🐛 [BUG] : Over flowing page in terms and contirions, cookies, deletion, and privacy

### ISSUE THREAD

**Issue by xuelink** [langx/website#41]
**Describe the bug**
The pages for terms and conditions, cookies, deletion, and privacy are overflowing. This issue is observed in Vivaldi and Chrome browsers. The actual resolution is unknown.

**To Reproduce**
1. Go to 'Terms and Conditions' (or 'Cookies', 'Deletion', 'Privacy')
2. Scroll down the page
3. See the content overflowing

**Expected behavior**
The content of these pages should fit within the confines of the page, without any overflow.

**Screenshots**
<img src="https://github.com/languageXchange/website/assets/3280475/be6bf2a3-1206-4994-be0f-8fbdc778c873" alt="Screenshot_20240304-124720" width="300px;">

<img src="https://github.com/languageXchange/website/assets/3280475/6a197587-aa93-4548-b653-c1d1cee042dc" alt="Screenshot_20240304-124814" width="300px;">

**Smartphone (please complete the following information):**
Browser: Vivaldi, Chrome

**Additional context**
_Contributor: @dev-vaganov_

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
> @xuelink I made a PR [here](https://github.com/langx/website/pull/64)

i think this PR fixes only footer centered social media icons, am i wrong ? did you fix that issue as well ? @jakebogan01

**Comment by jakebogan01** [comment]
@xuelink Yes I fixed the footer icons as well as the overflowing of the page issue. I just did both fixes in on PR

**Comment by xuelink** [comment]
> @xuelink Yes I fixed the footer icons as well as the overflowing of the page issue. I just did both fixes in on PR

Thank you very much, it works @jakebogan01

**Comment by jakebogan01** [comment]
@xuelink no problem 👍
