### ISSUE TITLE
🚀 : API Integration for Newsletter Subscription

### ISSUE THREAD

**Issue by xuelink** [langx/website#62]
**Is your feature request related to a problem? Please describe.**
The platform lacks a seamless way for users to join the newsletter, hindering efforts to grow and engage with the audience effectively.

**Describe the solution you'd like**
Implement an API that allows users to easily subscribe to the newsletter directly from the platform. This API should facilitate a smooth integration between the platform and the newsletter service, enabling users to opt-in with minimal effort.

**Describe alternatives you've considered**
Alternative solutions may include manual subscription forms or redirects to external newsletter subscription pages. However, these methods are often cumbersome and may result in a lower conversion rate.

**Additional context**
By integrating an API for newsletter subscription, the platform can streamline the user experience and increase newsletter sign-ups. This feature would not only help in expanding the subscriber base but also enhance communication with users, leading to improved engagement and retention.

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
Related w/ #30 and #61

**Comment by jakebogan01** [comment]
@xuelink no worries, been busy myself last couple of days
