### ISSUE TITLE
🚀 : Add Huawei logo to the section of "Verified by Leading Companies Worldwide"

### ISSUE THREAD

**Issue by xuelink** [langx/website#70]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the "Verified by Leading Companies Worldwide" section does not include prominent companies that have verified us, as it affects the perceived credibility and trustworthiness of our platform.

<img width="1063" alt="Screenshot 2024-05-24 at 2 51 48 PM" src="https://github.com/langx/website/assets/3280475/365464fc-0fad-4cc5-91f7-3f7e00e28c58">

**Describe the solution you'd like**
I would like to add the Huawei logo to the "Verified by Leading Companies Worldwide" section on our website. This addition will showcase our verification by a leading global company, enhancing our platform's credibility.

![a951fd885a2ac2577c8bac8dbe01ae42](https://github.com/langx/website/assets/3280475/3a13b69d-cd54-45f5-a644-9f61b404fc77)

**Describe alternatives you've considered**
As an alternative, we considered including a broader range of logos from other verified companies in the section. However, adding the Huawei logo specifically will have a significant impact due to its global recognition.

**Additional context**
Here is the Huawei logo to be added to the section:

_If you want to speed up the process of this issue, please send 🚀 as a reaction._

**Comment by xuelink** [comment]
Related w/ https://github.com/langx/langx/issues/690
<img width="435" alt="Screenshot 2024-05-24 at 2 55 52 PM" src="https://github.com/langx/website/assets/3280475/7e4ab5cd-13bd-4de8-8e50-d4bf34ffa601">

**Comment by xuelink** [comment]
I ve checked and @jakebogan01 did `Created with Sketch.` so i think it is easy for you to add this logo as well that's why i assigned this issue to you :) if you do, i appriciate.

**Comment by jakebogan01** [comment]
@xuelink I made a PR [here](https://github.com/langx/website/pull/71)
